# https://medium.com/app-dev-community/configuring-travis-ci-for-android-project-api-level-30-c4e37c544b26
# https://stackoverflow.com/questions/53076422/getting-android-sdkmanager-to-run-with-java-11
# https://stackoverflow.com/questions/54273412/failed-to-install-the-following-android-sdk-packages-as-some-licences-have-not
# https://stackoverflow.com/questions/12343452/how-to-publish-artifacts-in-travis-ci
# https://medium.com/@tjkangs/travisci-circleci-2-0-with-fastlane-for-react-native-both-ios-and-android-3f99b71b8691

sudo: required
language: android
jdk: oraclejdk17
dist: trusty

android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
 
  components:
    - tools
    - platform-tools
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

env:
  global:
    - TARGET_VERSION=30
    - ANDROID_BUILD_TOOLS_VERSION=30.0.2
    - ANDROID_HOME=~/android-sdk
 
install:
  - yarn install

before_install:
  - nvm install 16
  - node --version
  - npm --version
  # - travis_retry curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
  # - echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  # - travis_retry sudo apt-get update -qq
  # - travis_retry sudo apt-get install -y -qq yarn
  # - yes | sdkmanager --licenses
  # -  yes | ~/Android/Sdk/tools/bin/sdkmanager --licenses
  - touch $HOME/.android/repositories.cfg
  - wget "https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip" -O commandlinetools.zip
  - unzip commandlinetools.zip -d $ANDROID_HOME/
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platforms;android-${TARGET_VERSION}" --sdk_root=$ANDROID_HOME
  - yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" --sdk_root=$ANDROID_HOME


before_script:
  - npm install
  - chmod +x ./android/gradlew
#   - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
#   - emulator -avd test -no-audio -no-window &
#   - android-wait-for-emulator
#   - adb shell input keyevent 82 &

script:
  # - ./gradlew test
  - cd android && bash ./gradlew assembleRelease --stacktrace

# branches:
#   only:
#   - master
  
notifications:
  email:
    on_success: never
    on_failure: always

deploy:
  provider: releases
  api_key: ${github_api_key}
  file: "android/app/build/outputs/apk/release/app-release.apk"
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
