# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://github.com/realabbas/Github-Actions-React-Native
# https://blog.usejournal.com/automate-react-native-builds-with-github-actions-af54212d26dc
# https://blog.logrocket.com/react-native-ci-cd-using-github-actions/

name: react-native-android-build-apk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Setup JDK
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && bash ./gradlew assembleRelease --stacktrace
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
